spring.application.name=payment-api

spring.datasource.url=jdbc:postgresql://localhost:5432/pagamentos
spring.datasource.username=admin
spring.datasource.password=admin123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.prometheus.access=READ_ONLY
management.prometheus.metrics.export.enabled=true